const fs = require('fs');
const pdf = require('html-pdf');

const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rohit Kumar - Professional CV</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1, h2 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        .contact-info {
            text-align: center;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .job-title {
            font-weight: bold;
            color: #2980b9;
        }
        .company {
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="contact-info">
        <h1>Rohit Kumar</h1>
        <p>📍 Location: India | 📧 Email: contact@viperdimension.com</p>
        <p>🌐 Portfolio: https://viperdimension.com | 💼 LinkedIn: rohit-kumar</p>
    </div>

    <div class="section">
        <h2>Professional Summary</h2>
        <p>Innovative software engineer with expertise in full-stack development, cybersecurity, and AI technologies. Proven track record of delivering robust solutions and driving technological innovation.</p>
    </div>

    <div class="section">
        <h2>Technical Skills</h2>
        <ul>
            <li><strong>Programming Languages:</strong> Python, JavaScript, TypeScript, Java, C++</li>
            <li><strong>Web Technologies:</strong> React, Node.js, Express, HTML5, CSS3, Tailwind</li>
            <li><strong>Databases:</strong> MongoDB, PostgreSQL, MySQL</li>
            <li><strong>Cloud & DevOps:</strong> AWS, Docker, Kubernetes, Git</li>
            <li><strong>Cybersecurity:</strong> Penetration Testing, Network Security, Ethical Hacking</li>
        </ul>
    </div>

    <div class="section">
        <h2>Professional Experience</h2>
        
        <div>
            <p class="job-title">Software Development Intern, ISRO</p>
            <p class="company">Indian Space Research Organisation</p>
            <ul>
                <li>Developed advanced data processing algorithms for satellite imagery</li>
                <li>Collaborated with senior scientists to enhance mission-critical software systems</li>
                <li>Implemented machine learning models for predictive analysis</li>
            </ul>
        </div>

        <div>
            <p class="job-title">Cybersecurity Researcher</p>
            <p class="company">Viper Imagination</p>
            <ul>
                <li>Conducted comprehensive security assessments for multiple digital platforms</li>
                <li>Developed custom security solutions using advanced threat detection techniques</li>
                <li>Created robust encryption protocols for sensitive data protection</li>
            </ul>
        </div>
    </div>

    <div class="section">
        <h2>Certifications</h2>
        <ul>
            <li>University of Michigan - Python Data Structures</li>
            <li>IBM - Cybersecurity Tools & Cyber Attacks</li>
            <li>Google - Python Certification</li>
            <li>University of Michigan - Python for Everybody</li>
        </ul>
    </div>

    <div class="section">
        <h2>Education</h2>
        <p>Bachelor of Technology in Computer Science</p>
        <p>Specialization in Cybersecurity and Artificial Intelligence</p>
    </div>

    <div class="section">
        <h2>Projects</h2>
        <ul>
            <li>Personal Portfolio Website (https://viperdimension.com)</li>
            <li>Advanced Cybersecurity Threat Detection System</li>
            <li>Machine Learning-based Image Recognition Platform</li>
        </ul>
    </div>

    <footer>
        <p><em>Generated by Viper Imagination - Professional CV Generator</em></p>
    </footer>
</body>
</html>
`;

const options = {
    format: 'A4',
    orientation: 'portrait',
    border: {
        top: "10mm",
        right: "10mm",
        bottom: "10mm",
        left: "10mm"
    }
};

pdf.create(html, options).toFile('./public/downloads/rohit-kumar-cv.pdf', (err, res) => {
    if (err) return console.log(err);
    console.log(res);
});
